In [117]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns       
import sklearn
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, PolynomialFeatures


from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [118]:
df = pd.read_csv('Data/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [119]:
df1 = pd.read_csv('Data/test.csv')
df1.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [120]:
women = df.loc[df.Sex == 'female']['Survived']
rate_women = sum(women) / len(women)

print(rate_women)

0.7420382165605095

In [121]:
men = df.loc[df.Sex == 'male']['Survived']
rate_men = sum(men) / len(men)
print(rate_men)

0.18890814558058924

KNN

In [122]:
##Data cleaning

df['Age'] = df['Age'].fillna(df['Age'].median())
df1['Age'] = df1['Age'].fillna(df['Age'].median())

df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df1['Fare'] = df1['Fare'].fillna(df1['Fare'].median())



df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df1['Sex'] = df1['Sex'].map({'male': 0, 'female': 1})

In [123]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
x_train = df[features]
y_train = df['Survived']

x_test = df1[features]

scalar = StandardScaler()
x_scaled = scalar.fit_transform(x_train)
x_test_scaled = scalar.transform(x_test)

In [124]:
max_k = 30
scores = []
for k in range(1, max_k + 1):
    model = KNeighborsClassifier(n_neighbors=k)
    score = cross_val_score(model, x_train, y_train, cv=5, scoring='accuracy')
    scores.append(score.mean())

best_k = scores.index(max(scores)) + 1

print(f"Best k: {best_k}")

Best k: 22

In [129]:
model = KNeighborsClassifier(n_neighbors=best_k)
model.fit(x_scaled, y_train)

preds = model.predict(x_test_scaled)

In [132]:
submission = pd.DataFrame({
    'PassengerId': df1['PassengerId'],
    'Survived': preds
})

submission.to_csv('knn_submission.csv', index=False)